# Generated by Django 3.1.5 on 2022-02-25 16:40

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_register_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(blank=True, choices=[('HOT', 'hot'), ('COLD', 'cold'), ('MEDIUM', 'med'), ('SOLD', 'sold')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='register',
            managers=[
                ('obj', authentication.models.user_manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='pnum',
        ),
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone no.'),
        ),
        migrations.AddField(
            model_name='register',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('SA', 'Sales Admin'), ('SR', 'Sales Representative')], default='SR', max_length=2),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='register',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='lname',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField()),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lead')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.register')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.register'),
        ),
    ]
