# Generated by Django 3.1.5 on 2022-02-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220225_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.register'),
        ),
    ]
